[project]
name = "dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.10.13",
    "dbt-duckdb==1.9.6",
    "duckdb==1.4.1",
]
